pub mod account;
pub mod achievement;
pub mod afdian;
pub mod auth;
pub mod arena;
pub mod attribute;
pub mod battle;
pub mod battle_pass;
pub mod battle_session;
pub mod character;
pub mod character_technique;
pub mod dungeon;
pub mod game;
pub mod info;
pub mod insight;
pub mod idle;
pub mod inventory;
pub mod mail;
pub mod market;
pub mod map;
pub mod main_quest;
pub mod month_card;
pub mod partner;
pub mod rank;
pub mod realm;
pub mod redeem_code;
pub mod routes;
pub mod security;
pub mod sign_in;
pub mod slow_request;
pub mod sect;
pub mod task;
pub mod technique;
pub mod team;
pub mod time;
pub mod tower;
pub mod title;
pub mod upload;
pub mod wander;

use axum::{Router, middleware, routing::{delete, get, post, put}};

use crate::state::AppState;

pub fn router() -> Router<AppState> {
    Router::new()
        .route("/", get(routes::root))
        .route("/api/health", get(routes::health))
        .route("/api/captcha/config", get(auth::get_captcha_config))
        .route("/api/auth/captcha", get(auth::get_captcha))
        .route("/api/auth/register", post(auth::register))
        .route("/api/auth/login", post(auth::login))
        .route("/api/auth/verify", get(auth::verify))
        .route("/api/auth/bootstrap", get(auth::bootstrap))
        .route("/api/account/current-ip", get(account::get_current_ip))
        .route("/api/account/phone-binding/send-code", post(account::send_phone_binding_code))
        .route("/api/account/phone-binding/status", get(account::get_phone_binding_status))
        .route("/api/account/phone-binding/bind", post(account::bind_phone_number))
        .route("/api/account/password/change", post(account::change_password))
        .route("/api/achievement/claim", post(achievement::claim_achievement_reward))
        .route("/api/achievement/list", get(achievement::get_achievement_list))
        .route("/api/achievement/{achievementId}", get(achievement::get_achievement_detail))
        .route("/api/achievement/points/claim", post(achievement::claim_achievement_points_reward))
        .route("/api/achievement/points/rewards", get(achievement::get_achievement_points_rewards))
        .route("/api/arena/status", get(arena::get_arena_status))
        .route("/api/arena/opponents", get(arena::get_arena_opponents))
        .route("/api/arena/records", get(arena::get_arena_records))
        .route("/api/arena/challenge", post(arena::start_arena_challenge))
        .route("/api/arena/match", post(arena::start_arena_match))
        .route("/api/attribute/add", post(attribute::add))
        .route("/api/attribute/remove", post(attribute::remove))
        .route("/api/attribute/batch", post(attribute::batch))
        .route("/api/attribute/reset", post(attribute::reset))
        .route("/api/battle/abandon", post(battle::abandon_battle))
        .route("/api/battle/action", post(battle::battle_action))
        .route("/api/battle/start", post(battle::start_pve_battle))
        .route("/api/battlepass/tasks/{taskId}/complete", post(battle_pass::complete_battle_pass_task))
        .route("/api/battlepass/claim", post(battle_pass::claim_battle_pass_reward))
        .route("/api/battlepass/status", get(battle_pass::get_battle_pass_status))
        .route("/api/battlepass/rewards", get(battle_pass::get_battle_pass_rewards))
        .route("/api/battlepass/tasks", get(battle_pass::get_battle_pass_tasks))
        .route("/api/battle-session/current", get(battle_session::get_current_battle_session))
        .route("/api/battle-session/start", post(battle_session::start_battle_session))
        .route("/api/battle-session/by-battle/{battleId}", get(battle_session::get_battle_session_by_battle_id))
        .route("/api/battle-session/{sessionId}", get(battle_session::get_battle_session_by_id))
        .route("/api/battle-session/{sessionId}/advance", post(battle_session::advance_battle_session))
        .route("/api/character/check", get(character::check))
        .route("/api/character/info", get(character::info))
        .route("/api/character/create", post(character::create))
        .route("/api/character/updatePosition", post(character::update_position))
        .route("/api/character/updateAutoCastSkills", post(character::update_auto_cast_skills))
        .route("/api/character/updateAutoDisassemble", post(character::update_auto_disassemble))
        .route("/api/character/updateDungeonNoStaminaCost", post(character::update_dungeon_no_stamina_cost))
        .route("/api/character/renameWithCard", post(character::rename_with_card))
        .route("/api/character/{characterId}/technique/status", get(character_technique::get_character_technique_status))
        .route("/api/character/{characterId}/technique/research/generate", post(character_technique::generate_technique_research_draft))
        .route("/api/character/{characterId}/technique/research/generate/{generationId}/discard", post(character_technique::discard_technique_research_draft))
        .route("/api/character/{characterId}/technique/research/generate/{generationId}/publish", post(character_technique::publish_technique_research_draft))
        .route("/api/character/{characterId}/technique/research/status", get(character_technique::get_technique_research_status))
        .route("/api/character/{characterId}/technique/research/mark-result-viewed", post(character_technique::mark_technique_research_result_viewed))
        .route("/api/character/{characterId}/techniques", get(character_technique::get_character_techniques))
        .route("/api/character/{characterId}/techniques/equipped", get(character_technique::get_equipped_techniques))
        .route("/api/character/{characterId}/technique/{techniqueId}/upgrade-cost", get(character_technique::get_character_technique_upgrade_cost))
        .route("/api/character/{characterId}/technique/{techniqueId}/upgrade", post(character_technique::upgrade_character_technique))
        .route("/api/character/{characterId}/technique/{techniqueId}/dissipate", post(character_technique::dissipate_character_technique))
        .route("/api/character/{characterId}/technique/equip", post(character_technique::equip_character_technique))
        .route("/api/character/{characterId}/technique/unequip", post(character_technique::unequip_character_technique))
        .route("/api/character/{characterId}/skills/available", get(character_technique::get_available_skills))
        .route("/api/character/{characterId}/skills/equipped", get(character_technique::get_equipped_skills))
        .route("/api/character/{characterId}/skill/equip", post(character_technique::equip_character_skill))
        .route("/api/character/{characterId}/skill/unequip", post(character_technique::unequip_character_skill))
        .route("/api/character/{characterId}/technique/passives", get(character_technique::get_technique_passives))
        .route("/api/dungeon/categories", get(dungeon::get_dungeon_categories))
        .route("/api/dungeon/list", get(dungeon::get_dungeon_list))
        .route("/api/dungeon/preview/{id}", get(dungeon::get_dungeon_preview))
        .route("/api/dungeon/instance/create", post(dungeon::create_dungeon_instance))
        .route("/api/dungeon/instance/by-battle/{battleId}", get(dungeon::get_dungeon_instance_by_battle_id))
        .route("/api/dungeon/instance/abandon", post(dungeon::abandon_dungeon_instance))
        .route("/api/dungeon/instance/join", post(dungeon::join_dungeon_instance))
        .route("/api/dungeon/instance/next", post(dungeon::next_dungeon_instance))
        .route("/api/dungeon/instance/start", post(dungeon::start_dungeon_instance))
        .route("/api/dungeon/instance/{id}", get(dungeon::get_dungeon_instance))
        .route("/api/afdian/webhook", get(afdian::get_afdian_webhook))
        .route("/api/afdian/webhook", post(afdian::post_afdian_webhook))
        .route("/api/game/home-overview", get(game::get_game_home_overview))
        .route("/api/upload/avatar/sts", post(upload::get_avatar_upload_sts))
        .route("/api/upload/avatar-asset/sts", post(upload::get_avatar_asset_upload_sts))
        .route("/api/upload/avatar/confirm", post(upload::confirm_avatar_upload))
        .route("/api/upload/avatar-asset/confirm", post(upload::confirm_avatar_asset_upload))
        .route("/api/upload/avatar", post(upload::upload_avatar_local))
        .route("/api/upload/avatar-asset", post(upload::upload_avatar_asset_local))
        .route("/api/upload/avatar", delete(upload::delete_avatar_upload))
        .route("/api/info/item-taxonomy", get(info::get_item_taxonomy))
        .route("/api/info/{type}/{id}", get(info::get_info_target))
        .route("/api/insight/overview", get(insight::get_overview))
        .route("/api/insight/inject", post(insight::inject_exp))
        .route("/api/idle/status", get(idle::get_idle_status))
        .route("/api/idle/history", get(idle::get_idle_history))
        .route("/api/idle/history/{id}/viewed", post(idle::mark_idle_history_viewed))
        .route("/api/idle/progress", get(idle::get_idle_progress))
        .route("/api/idle/config", get(idle::get_idle_config))
        .route("/api/idle/config", put(idle::update_idle_config))
        .route("/api/idle/start", post(idle::start_idle_session))
        .route("/api/idle/stop", post(idle::stop_idle_session))
        .route("/api/inventory/info", get(inventory::get_inventory_info))
        .route("/api/inventory/bag/snapshot", get(inventory::get_bag_inventory_snapshot))
        .route("/api/inventory/items", get(inventory::get_inventory_items))
        .route("/api/inventory/use", post(inventory::use_inventory_item))
        .route("/api/inventory/disassemble/preview", post(inventory::preview_inventory_disassemble))
        .route("/api/inventory/disassemble", post(inventory::disassemble_inventory_item))
        .route("/api/inventory/disassemble/batch", post(inventory::disassemble_inventory_items_batch))
        .route("/api/inventory/growth/cost-preview", post(inventory::preview_inventory_growth_cost))
        .route("/api/inventory/reroll-affixes/cost-preview", post(inventory::preview_inventory_reroll_cost))
        .route("/api/inventory/reroll-affixes/pool-preview", post(inventory::preview_inventory_affix_pool))
        .route("/api/inventory/reroll-affixes", post(inventory::reroll_inventory_affixes))
        .route("/api/inventory/enhance", post(inventory::enhance_inventory_item))
        .route("/api/inventory/refine", post(inventory::refine_inventory_item))
        .route("/api/inventory/socket", post(inventory::socket_inventory_gem))
        .route("/api/inventory/gem/recipes", get(inventory::list_inventory_gem_synthesis_recipes))
        .route("/api/inventory/gem/convert/options", get(inventory::list_inventory_gem_convert_options))
        .route("/api/inventory/gem/synthesize", post(inventory::synthesize_inventory_gem))
        .route("/api/inventory/gem/synthesize/batch", post(inventory::synthesize_inventory_gem_batch))
        .route("/api/inventory/gem/convert", post(inventory::convert_inventory_gem))
        .route("/api/inventory/craft/recipes", get(inventory::list_inventory_craft_recipes))
        .route("/api/inventory/craft/execute", post(inventory::execute_inventory_craft_recipe))
        .route("/api/inventory/expand", post(inventory::expand_inventory))
        .route("/api/inventory/sort", post(inventory::sort_inventory))
        .route("/api/inventory/lock", post(inventory::set_inventory_item_locked))
        .route("/api/inventory/equip", post(inventory::equip_inventory_item))
        .route("/api/inventory/unequip", post(inventory::unequip_inventory_item))
        .route("/api/inventory/move", post(inventory::move_inventory_item))
        .route("/api/inventory/remove", post(inventory::remove_inventory_item))
        .route("/api/inventory/remove/batch", post(inventory::remove_inventory_items_batch))
        .route("/api/mail/list", get(mail::list_mails))
        .route("/api/mail/claim", post(mail::claim_mail_attachments))
        .route("/api/mail/claim-all", post(mail::claim_all_mail_attachments))
        .route("/api/mail/unread", get(mail::unread_counts))
        .route("/api/mail/delete", post(mail::delete_mail))
        .route("/api/mail/delete-all", post(mail::delete_all_mails))
        .route("/api/mail/read", post(mail::read_mail))
        .route("/api/mail/read-all", post(mail::read_all_mails))
        .route("/api/market/listings", get(market::get_market_listings))
        .route("/api/market/cancel", post(market::cancel_market_listing))
        .route("/api/market/list", post(market::create_market_listing))
        .route("/api/market/buy", post(market::buy_market_listing))
        .route("/api/market/my-listings", get(market::get_my_market_listings))
        .route("/api/market/records", get(market::get_market_trade_records))
        .route("/api/market/captcha", get(market::get_market_purchase_captcha))
        .route("/api/market/captcha/verify", post(market::verify_market_purchase_captcha))
        .route("/api/market/partner-listings", get(market::get_partner_market_listings))
        .route("/api/market/partner-my-listings", get(market::get_my_partner_market_listings))
        .route("/api/market/partner-records", get(market::get_partner_market_trade_records))
        .route("/api/market/partner/technique-detail", get(market::get_market_partner_technique_detail))
        .route("/api/market/partner/cancel", post(market::cancel_partner_market_listing))
        .route("/api/market/partner/list", post(market::create_partner_market_listing))
        .route("/api/market/partner/buy", post(market::buy_partner_market_listing))
        .route("/api/main-quest/progress", get(main_quest::get_main_quest_progress))
        .route("/api/main-quest/chapters", get(main_quest::get_main_quest_chapters))
        .route("/api/main-quest/chapters/{chapterId}/sections", get(main_quest::get_main_quest_sections))
        .route("/api/main-quest/dialogue/advance", post(main_quest::advance_main_quest_dialogue))
        .route("/api/main-quest/dialogue/choice", post(main_quest::choose_main_quest_dialogue_option))
        .route("/api/main-quest/dialogue/start", post(main_quest::start_main_quest_dialogue))
        .route("/api/main-quest/section/complete", post(main_quest::complete_main_quest_section))
        .route("/api/main-quest/track", post(main_quest::set_main_quest_tracked))
        .route("/api/map/world", get(map::get_world_map))
        .route("/api/map/maps", get(map::get_enabled_maps))
        .route("/api/map/{mapId}", get(map::get_map_detail))
        .route("/api/map/{mapId}/rooms/{roomId}", get(map::get_room_detail))
        .route("/api/map/{mapId}/rooms/{roomId}/objects", get(map::get_room_objects))
        .route("/api/map/{mapId}/rooms/{roomId}/resources/{resourceId}/gather", post(map::gather_room_resource))
        .route("/api/map/{mapId}/rooms/{roomId}/items/{itemDefId}/pickup", post(map::pickup_room_item))
        .route("/api/monthcard/status", get(month_card::get_month_card_status))
        .route("/api/monthcard/use-item", post(month_card::use_month_card_item))
        .route("/api/monthcard/claim", post(month_card::claim_month_card_reward))
        .route("/api/partner/overview", get(partner::get_partner_overview))
        .route("/api/partner/preview", get(partner::get_partner_preview))
        .route("/api/partner/recruit/generate", post(partner::generate_partner_recruit_draft))
        .route("/api/partner/recruit/{generationId}/confirm", post(partner::confirm_partner_recruit_draft))
        .route("/api/partner/recruit/status", get(partner::get_partner_recruit_status))
        .route("/api/partner/recruit/{generationId}/discard", post(partner::discard_partner_recruit_draft))
        .route("/api/partner/recruit/mark-result-viewed", post(partner::mark_partner_recruit_result_viewed))
        .route("/api/partner/fusion/status", get(partner::get_partner_fusion_status))
        .route("/api/partner/fusion/start", post(partner::start_partner_fusion))
        .route("/api/partner/fusion/{fusionId}/confirm", post(partner::confirm_partner_fusion_preview))
        .route("/api/partner/fusion/mark-result-viewed", post(partner::mark_partner_fusion_result_viewed))
        .route("/api/partner/rebone/status", get(partner::get_partner_rebone_status))
        .route("/api/partner/rebone/start", post(partner::start_partner_rebone))
        .route("/api/partner/rebone/mark-result-viewed", post(partner::mark_partner_rebone_result_viewed))
        .route("/api/partner/activate", post(partner::activate_partner))
        .route("/api/partner/dismiss", post(partner::dismiss_partner))
        .route("/api/partner/inject-exp", post(partner::inject_partner_exp))
        .route("/api/partner/learn-technique", post(partner::learn_partner_technique))
        .route("/api/partner/learn-technique/confirm", post(partner::confirm_partner_technique_learn_preview))
        .route("/api/partner/learn-technique/discard", post(partner::discard_partner_technique_learn_preview))
        .route("/api/partner/renameWithCard", post(partner::rename_partner_with_card))
        .route("/api/partner/skill-policy", get(partner::get_partner_skill_policy))
        .route("/api/partner/skill-policy", put(partner::update_partner_skill_policy))
        .route("/api/partner/technique-upgrade-cost", get(partner::get_partner_technique_upgrade_cost))
        .route("/api/partner/technique-detail", get(partner::get_partner_technique_detail))
        .route("/api/partner/upgrade-technique", post(partner::upgrade_partner_technique))
        .route("/api/rank/overview", get(rank::get_rank_overview))
        .route("/api/rank/realm", get(rank::get_realm_ranks_handler))
        .route("/api/rank/sect", get(rank::get_sect_ranks_handler))
        .route("/api/rank/wealth", get(rank::get_wealth_ranks_handler))
        .route("/api/rank/arena", get(rank::get_arena_ranks_handler))
        .route("/api/rank/partner", get(rank::get_partner_ranks_handler))
        .route("/api/redeem-code/redeem", post(redeem_code::redeem_code))
        .route("/api/realm/breakthrough", post(realm::breakthrough))
        .route("/api/realm/overview", get(realm::get_overview))
        .route("/api/signin/do", post(sign_in::do_sign_in))
        .route("/api/signin/overview", get(sign_in::get_overview))
        .route("/api/sect/me", get(sect::get_my_sect))
        .route("/api/sect/search", get(sect::search_sects))
        .route("/api/sect/create", post(sect::create_sect_handler))
        .route("/api/sect/disband", post(sect::disband_sect_handler))
        .route("/api/sect/donate", post(sect::donate_to_sect_handler))
        .route("/api/sect/announcement/update", post(sect::update_sect_announcement_handler))
        .route("/api/sect/appoint", post(sect::appoint_sect_position_handler))
        .route("/api/sect/buildings/list", get(sect::get_sect_buildings))
        .route("/api/sect/buildings/bless", post(sect::offer_sect_blessing_handler))
        .route("/api/sect/buildings/upgrade", post(sect::upgrade_sect_building_handler))
        .route("/api/sect/bonuses", get(sect::get_sect_bonuses_handler))
        .route("/api/sect/{sectId}", get(sect::get_sect_info_handler))
        .route("/api/sect/applications/list", get(sect::list_sect_applications))
        .route("/api/sect/applications/mine", get(sect::list_my_sect_applications))
        .route("/api/sect/apply", post(sect::apply_to_sect_handler))
        .route("/api/sect/applications/cancel", post(sect::cancel_my_application_handler))
        .route("/api/sect/applications/handle", post(sect::handle_sect_application_handler))
        .route("/api/sect/kick", post(sect::kick_sect_member_handler))
        .route("/api/sect/logs", get(sect::get_sect_logs_handler))
        .route("/api/sect/leave", post(sect::leave_sect_handler))
        .route("/api/sect/shop/buy", post(sect::buy_from_sect_shop_handler))
        .route("/api/sect/transfer", post(sect::transfer_sect_leader_handler))
        .route("/api/sect/quests/accept", post(sect::accept_sect_quest_handler))
        .route("/api/sect/quests/claim", post(sect::claim_sect_quest_handler))
        .route("/api/sect/quests", get(sect::get_sect_quests_handler))
        .route("/api/sect/quests/submit", post(sect::submit_sect_quest_handler))
        .route("/api/sect/shop", get(sect::get_sect_shop_handler))
        .route("/api/task/claim", post(task::claim_task_reward))
        .route("/api/task/npc/accept", post(task::npc_accept))
        .route("/api/task/overview", get(task::get_task_overview))
        .route("/api/task/overview/summary", get(task::get_task_overview_summary))
        .route("/api/task/npc/submit", post(task::npc_submit))
        .route("/api/task/npc/talk", post(task::npc_talk))
        .route("/api/task/track", post(task::set_task_tracked))
        .route("/api/team/my", get(team::get_my_team))
        .route("/api/team/{teamId}", get(team::get_team_by_id_handler))
        .route("/api/team/create", post(team::create_team_handler))
        .route("/api/team/disband", post(team::disband_team_handler))
        .route("/api/team/apply", post(team::apply_to_team_handler))
        .route("/api/team/applications/{teamId}", get(team::get_team_applications_handler))
        .route("/api/team/application/handle", post(team::handle_team_application_handler))
        .route("/api/team/kick", post(team::kick_team_member_handler))
        .route("/api/team/invite", post(team::invite_to_team_handler))
        .route("/api/team/invitation/handle", post(team::handle_team_invitation_handler))
        .route("/api/team/leave", post(team::leave_team_handler))
        .route("/api/team/settings", post(team::update_team_settings_handler))
        .route("/api/team/transfer", post(team::transfer_team_leader_handler))
        .route("/api/team/nearby/list", get(team::get_nearby_teams_handler))
        .route("/api/team/lobby/list", get(team::get_lobby_teams_handler))
        .route("/api/team/invitations/received", get(team::get_received_invitations_handler))
        .route("/api/technique", get(technique::get_enabled_techniques))
        .route("/api/technique/{techniqueId}", get(technique::get_technique_detail))
        .route("/api/time", get(time::get_time))
        .route("/api/tower/overview", get(tower::get_tower_overview))
        .route("/api/tower/rank", get(tower::get_tower_rank))
        .route("/api/tower/challenge/start", post(tower::start_tower_challenge))
        .route("/api/title/list", get(title::get_title_list))
        .route("/api/title/equip", post(title::equip_title))
        .route("/api/wander/overview", get(wander::get_wander_overview))
        .route("/api/wander/generate", post(wander::create_wander_generation_job))
        .route("/api/wander/choose", post(wander::choose_wander_episode_option))
        .layer(middleware::from_fn(slow_request::log_slow_request))
}
